#! /bin/sh

killall polybar
pgrep -x sxhkd > /dev/null || sxhkd &
#wal -i /home/devinda/Downloads/bg.jpg
wal -i "$(< "${HOME}/.cache/wal/wal")"

bspc monitor DP-2 -d www code fun                 
bspc monitor DP-0 -d www code fun
bspc monitor HDMI-2 -d www code fun 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config window_gap 20
bspc config border_width 10
bspc config focused_border_color   "#97B5BA"
bspc config active_border_color    "#3D6488"
bspc config normal_border_color    "#3D6488"


xsetroot -cursor_name left_ptr
picom -b &
polybar tray > /dev/null &
polybar HDMI-Windows > /dev/null &
polybar DP-Windows > /dev/null &
numlockx
